---
- name: 'Prepare things like SSH keys for easy bundlewrap testing'
  hosts: 'all'
  gather_facts: true
  become: false

  tasks:

    - name: 'Create directory /home/vagrant/.ssh/'
      ansible.builtin.file:
        path: '/home/vagrant/.ssh/'
        state: 'directory'
        owner: 'vagrant'
        group: 'vagrant'
        mode: '0700'

    - name: 'Create a SSH key for the vagrant user'
      community.crypto.openssh_keypair:
        path: '/home/vagrant/.ssh/id_ed25519'
        type: 'ed25519'
        passphrase: ''
        comment: "vagrant user on {{ inventory_hostname }}"

    - name: 'Slurp the public ssh key'
      ansible.builtin.slurp:
        src: '/home/vagrant/.ssh/id_ed25519.pub'
      register: ed25519_public_key

    - name: "Add the new key to the vagrant user's authorized_key file"
      ansible.posix.authorized_key:
        user: 'vagrant'
        state: 'present'
        key: " {{ ed25519_public_key.content | b64decode }}"

    - name: 'Slurp the public ed25519 host key'
      ansible.builtin.slurp:
        src: '/etc/ssh/ssh_host_ed25519_key.pub'
      register: ssh_host_ed25519_key_pub

    - name: 'Make sure the SSH host key is in /home/vagrant/.ssh/known_hosts'
      ansible.builtin.lineinfile:
        path: '/home/vagrant/.ssh/known_hosts'
        line: "{{ item + ' ssh-ed25519 ' + (ssh_host_ed25519_key_pub.content | b64decode | split(' '))[1] }}"
        create: true
        owner: 'vagrant'
        group: 'vagrant'
        mode: '0600'
      loop:
        - 'localhost'
        - 'bundlewrap'
        - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
